### ISSUE TITLE
Crashes immediately upon launching

### ISSUE THREAD

**Issue by JamesIV4** [AgelessArchangel/RomSearch-for-RG35xx-Garlic-OS#1]
The app isn't launching successfully for me. I'm on GarlicOS 1.4.7 (I don't need the extra cores added in 1.4.8 and 1.4.9).

I'm suspecting it might be related to my settings.json file, since I have custom layout (./CFW/skin/settings.json). I'm going to try reverting my theme to stock and see if that helps.

I'm on a single-card setup and have tried v2 and v3 for good measure. Installed as expected (dropping folders into ROM partition).

Edit: I updated to GarlicOS 1.4.9 just for kicks, no luck there, and tried using the basic settings.json from the default theme, and no luck there either.

**Comment by AgelessArchangel** [comment]
Thank you!!
Please check if you have the font "/mnt/mmc/CFW/font/Joystix-Monospace.otf"
I have uploaded v0.3 again. Please try to download again.

I'm also on an older Garlic OS version!

**Comment by JamesIV4** [comment]
That fixed it!

**Comment by AgelessArchangel** [comment]
thanks. A new release is coming in  1-2 days.

**Comment by AgelessArchangel** [comment]
Done. Font was missing.
