### ISSUE TITLE
Feature request: theme font, image z-index, overlapping system logo and game logo

### ISSUE THREAD

**Issue by JamesIV4** [AgelessArchangel/RomSearch-for-RG35xx-Garlic-OS#2]
Hey again,

I had a try and it looks great! Very usable and useful.

I noticed a couple little things that are on my wish list:
- Can it use the font specified by the theme? That would improve readability and integration with the rest of the system
- I noticed the button help icons are underneath the thumbnail preview
- System logo overlaps with game logo names on the popular RG35XX thumbnail presets. Can it move to the bottom instead?
[Screenshot](https://i.imgur.com/JXQ7qsM.jpg)

**Comment by AgelessArchangel** [comment]
Thank you for the suggestions. 
- Can it use the font specified by the theme? That would improve readability and integration with the rest of the system
Yes! That was my intent.  Will be done in the next release

- I noticed the button help icons are underneath the thumbnail preview
This is a mistake. I will fix this.

- System logo overlaps with game logo names on the popular RG35XX thumbnail presets. Can it move to the bottom instead?
I will make it configurable in the skin file

**Comment by JamesIV4** [comment]
Nice! That sounds great!
