### ISSUE TITLE
Theme Buttons not alighning

### ISSUE THREAD

**Issue by rtakehara** [AgelessArchangel/RomSearch-for-RG35xx-Garlic-OS#3]
The Search app works wonders, and its impressive that it attempts to even follow the theme, I would be happy with just the function, however, it doesn't seem to follow garlic's alignments 1:1

Garlic button images anchor to the bottom (and text anchors to the center of the image) but the Search app anchors the images from the top (and text is fixed)

So, when I made the buttons shorter to have a slimmer bottom bar, it didn't translate well into the Search app

here's some images to better illustrate my issue

This is how it looks:
![Search_001](https://github.com/AgelessArchangel/RomSearch-for-RG35xx-Garlic-OS/assets/49849179/a3eb8676-53c6-4da1-87ba-78e03047fad3)

I made the Dpad and A buttons super tall, Dpad anchored to the bottom and A button anchored to the top, to see whats going on, notice how the D pad looks unchanged while the A changed its position even though both are equally high, and both have text misaligned
![GarlicOS_000](https://github.com/AgelessArchangel/RomSearch-for-RG35xx-Garlic-OS/assets/49849179/384e7b9c-b344-418f-b042-52c1648068e8)

![Search_000](https://github.com/AgelessArchangel/RomSearch-for-RG35xx-Garlic-OS/assets/49849179/278585da-c588-401d-91f3-6f41e15397b0)

Anyway, great job! Garlic was needing this feature!

**Comment by AgelessArchangel** [comment]
Thanks for the feedback.
Could you please send me the theme? I am not using all the main theme "items..". as you said, I am only "mimicking" the main theme. I can also see that the text color is incorrect. But for sure I can improve this. 
Thanks!
Please use v1.1 I guess this will solve your problem, however I would still appreciate if you can send me your theme.

**Comment by rtakehara** [comment]
I am using [MonoScreen Light](https://github.com/rtakehara/garlicOS-MonoScreen-Theme), but yeah I was using v1.0, it seems to be fixed in v1.1

yeah I also noticed the text colors too, the colors, at least for me, dont show up correctly in any skin. but in light or colorful skins it is more noticable (like this one, tech dweeb)

**Comment by AgelessArchangel** [comment]
Thank you for the reply. I will look into it and fix it.
BTW, from what I can tell, it seems that the app is not finding the settings.json from the main skin....
The app looks in /mnt/mmc/CFW/skin as the default location. If it cannot find the file, it will load its own file (./res/settings)
Does your skin folder have a different name? 
This is how it looks for me.
![example2](https://github.com/AgelessArchangel/RomSearch-for-RG35xx-Garlic-OS/assets/134300555/1f554846-4a49-4f41-9da0-80321c0ece60)

**Comment by AgelessArchangel** [comment]
Colors are now in sync with the main theme. Please use v1.2.
A few hints:
The app will try to load the files from /mnt/mmc/CFW/skin.
If a file is not found it will look for it in the 'local" folder ./res.

If you have issues with your theme and the app does not find the files in the SKIN location, you can adjust everything from these local files:
./res/settings.json    (below I added the the values for your theme)
{
	"text-alignment": "left",         
	"text-margin": 352,
	"color-guide": "#232323",,                                   // This is used for MOVE/OPEN/BACK/KEYBOARD.
	"color-inactive": "#808080",                                // This is used for the Unselected ROM in the ROM list.
	"color-active": "#00467E"                                     // This is used for the Selected Rom in the ROM list.
}


and ./skin.json.  (here you can adjust the colors of the keyboard)
{
	"color-background": "#343434",
	"color-searchbox-frame": "#464448",
	"color-searchbox": "#232323",
	"color-search-text": "#dcdcdc",
	"color-key": "#464448",
	"color-selected-key-text": "#7d7d7d",
	"color-unselected-key-text": "#dcdcdc",
	"color-text-info": "#7d7d7d",
	"color-cursor": "#dcdcdc", 
	"keyboard-and-result-pos-y": 105,
	"system-pos-x": 435,
	"system-pos-y": 25,
	"hide-helper-buttons": 0
}

**Comment by rtakehara** [comment]
ah, great work! Thanks!

I found that the if the last object in the settings.json in /CFW/skin doesn't end with `,`, it will not align the text for some reason

**Comment by AgelessArchangel** [comment]
Thanks, I will look into it... Strange_ When you say text is not aligned? Do you mean the ROM list? the text of the helper buttons?  
I think you are practically invalidating the /CFW/skin/settings.json so the local one is used... 
I will be back  with an update.
Is this how your settings.json look?
{
	"iso-code": "en_us",	
	"font": "font.ttf",
	**"text-alignment": "left",**        // maybe this is not set to what you expect
	"text-margin": 230,                        // and this
	"color-guide": "#232323",
	"color-inactive": "#808080",
	"color-active": "#00467E",
	"color-favorite-inactive": "#313131",
	"color-favorite-active": "#00467E",
	"empty-label": "Nothing to see here! Move along!",
	"savestates-unsupported": "This core doesn't support savestates!"
}


Thanks again.

**Comment by rtakehara** [comment]
The ROM list, showing is easier than describing so here's some screenshots

![Search_001](https://github.com/AgelessArchangel/RomSearch-for-RG35xx-Garlic-OS/assets/49849179/a403604d-1ebd-46ba-bd8d-81d16738eb88)

This is when the /CFW/skin/settings.json is like this:

```json
{
	"iso-code": "en_us",	
	"font": "font.ttf",
	"text-alignment": "left",
	"text-margin": 230,
	"color-guide": "#232323",
	"color-inactive": "#808080",
	"color-active": "#00467E",
	"color-favorite-inactive": "#313131",
	"color-favorite-active": "#00467E",
	"empty-label": "Nothing to see here! Move along!",
	"savestates-unsupported": "This core doesn't support savestates!",
}

```

![Search_000](https://github.com/AgelessArchangel/RomSearch-for-RG35xx-Garlic-OS/assets/49849179/267c7a65-f393-4118-9d90-bcc10896d8bf)

and this is when the json is like this:

```json
{
	"iso-code": "en_us",	
	"font": "font.ttf",
	"text-alignment": "left",
	"text-margin": 230,
	"color-guide": "#232323",
	"color-inactive": "#808080",
	"color-active": "#00467E",
	"color-favorite-inactive": "#313131",
	"color-favorite-active": "#00467E",
	"empty-label": "Nothing to see here! Move along!",
	"savestates-unsupported": "This core doesn't support savestates!"
}

```

The only difference is the `,` in the last entry, it's no big deal though

**Comment by AgelessArchangel** [comment]
This is normal behavior I think. The text aligns due to these configurations in the /mnt/mmc/CFW/settings.json :
"text-alignment": "left",
"text-margin": 230,
I expect the text has the same alignment also in the main SW. You should see the same behavior in any other list!!
You can see this in your own screenshot: (230 pixels from left - less than half the screen; you can use the grid as guideline... about 16 squares = 640px  => about 38px per square => 6*38 => about 230 pixels)
![z](https://github.com/AgelessArchangel/RomSearch-for-RG35xx-Garlic-OS/assets/134300555/0da523c9-c7dd-4950-8d2a-e9fec7d95545)


These configurations mean justify text to the left and offset 230 pixels. 
You can change the value of the "text-margin" to 352 (depending on what screenshots you use).

thank you very much for investigation and support. 
If everything is ok on your side, I will close this issue.
P.S. The app does not align the text to the keyboard!! it uses the alignment you have in the main app....You can think of the keyboard as a "widget" that comes on top... It is not related to the size of the text... Making the keyboard follow the text size and position would be complicated... Honestly I cannot think of a good solution. 
![Screenshot from 2023-06-13 12-15-52](https://github.com/AgelessArchangel/RomSearch-for-RG35xx-Garlic-OS/assets/134300555/c4174c93-c70d-4c3b-b0ec-7ec196b0d42c)
The screenshot should be full screen in both diagrams...

**Comment by rtakehara** [comment]
ahh, I understand now, yeah, no issues now
