### ISSUE TITLE
"Read the readme file"

### ISSUE THREAD

**Issue by neothezero** [AgelessArchangel/RomSearch-for-RG35xx-Garlic-OS#4]
There's no readme in the .zip download :) 

Love this app for my 35xx, working awesome! Not having a search was the main reason i stuck with stock as long as i did. I only upgraded to garlic because I found out i wasnt losing this feature!

**Comment by AgelessArchangel** [comment]
Thank you! I will add the read me.

**Comment by AgelessArchangel** [comment]
Fixed.
