### ISSUE TITLE
Intermittent 'bug' when scrolling through search results.

### ISSUE THREAD

**Issue by BeejNhet** [AgelessArchangel/RomSearch-for-RG35xx-Garlic-OS#5]
1st of all, great work here so big congrats to @AgelessArchangel ! This is definitely an App on GarlicOS that I couldn't live without!

Just wanted to report that randomly, when scrolling through the ROM search results, the speed of scrolling up/down through the list of ROMs seems to go 'hyper' and speed up which results in skipping through at least a couple of ROMs in the list. Force exiting RomSearch then re-launching to perform a new search seems to fix but does tend to happen again every 2-3 searches.

Thanks and keep up the good work!

**Comment by AgelessArchangel** [comment]
Thank  you! I will look into it as soon as possible.

**Comment by AgelessArchangel** [comment]
Should be fixed in version 1.3. Please have a look. 
I will keep the bug open.

**Comment by BeejNhet** [comment]
Wow, thanks for the quick response!

Will test asap and let you know the outcome.

**Comment by AgelessArchangel** [comment]
Thank you!

**Comment by BeejNhet** [comment]
Ok, so have tested the new version quite extensively last night and hey presto! Can confirm that this issue has been fixed!

One thing I'd love to hopefully see (and sure others will) in a future version is the option to add ROMS to your 'Favorites' from the search list but otherwise, so far so good!

@AgelessArchangel thanks for giving this some time and again, for your top notch work!

All the best!

**Comment by AgelessArchangel** [comment]
Thank you for the testing and for the idea! I will consider it for the future :) .
I have to check how GarlicOS handles Favorites.
