### ISSUE TITLE
Possible to run on Batocera / Koriki ? 

### ISSUE THREAD

**Issue by SocialDamage** [AgelessArchangel/RomSearch-for-RG35xx-Garlic-OS#7]
Is it possible to run on Batocera or Koriki OS ? 
I tried starting the app but it simply closes, i already asked in the Koriki Repo but i didnt get an answer yet. Maybe you can explain what could be a possible problem ? 

Thanks a lot !

**Comment by AgelessArchangel** [comment]
Hello,
Unfortunately it is not possible. As the name implies it is for Garlic OS only.
